---
title: "MAT5317 Categorical Assignment 2"
author:
- Teng Li(7373086)
- Zhize Lu(300075114)
- Chutong Zhang(300311325)
output: bookdown::html_document2
header-includes:
- \renewcommand{\and}{\\}
- \usepackage{float}
- \floatplacement{figure}{H}
bibliography: References.bib
link-citations: yes
---

<style type="text/css">
.title, .author{text-align: center;}
body{font-size: 12pt;}
table{font-size: 12pt;}
h1{font-size: 14pt;}
h2{font-size: 12pt;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(tidyverse)
library(plotly)
library(kableExtra)
```

```{r}
CCAHS<-read.csv("CCAHS.csv", header = TRUE)
Covid<-read.csv("Covid.csv", header = TRUE)
WMortality<-read.csv("WeeklyMortality.csv", header = TRUE)
ExMortality<-read.csv("ExcessMortality.csv", header = TRUE)
LongTerm<-read.csv("LongTerm.csv", header = TRUE)
```

# Introduction

# Method

# Result
```{r}
WMortality%>%mutate(Year=year(REF_DATE), Week=substr(REF_DATE,6,10))%>%mutate(Year=factor(Year))%>%filter(Age.at.time.of.death=="Age at time of death, all ages" & Sex=="Both sexes" & GEO=="Canada, place of occurrence")%>%
  plot_ly(x=~Week, y=~VALUE, color=~Year,type = "scatter", mode="lines")
```

# Discussion

# Conclusion

# References
